#激活哪一个环境的配置文件
#默认测试环境
spring:

  resources:
    static-locations:classpath:static/,file:static/

  profiles:
    active: dev
  #公共配置
  thymeleaf:
    prefix: classpath:/static/
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100Mb
      max-request-size: 100Mb

  redis:
    # 连接超时时间（毫秒）
    timeout: 0
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
server:
  servlet:
    context-path: /crm_lanwo
  tomcat:
    max-threads: 10

jdbc:
  jdbcUrlPrefix: jdbc:mysql://
  jdbcUrlSuffix: ?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useAffectedRows=true&useSSL=false&serverTimezone=Hongkong&noAccessToProcedureBodies=true


mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.cyrj.*.pojo

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logging:
  level:
    com:
      cyrj:
        other:
          mapper: DEBUG
